### ISSUE TITLE
No devices found

### ISSUE THREAD

**Issue by Grey-Lancaster** [ppamment/wledcast#2]
C:\Users\Grey>WLEDCAST
No WLED instances found on the network.

If it makes any difference mDNS does not work on my laptop
I can ping by ip but device.local does not work

**Comment by ppamment** [comment]
If mDNS doesn't work on your computer you can pass the ip address with eg
```
wledcast --host=192.168.1.x
```

I'll update that to fall back to asking you to enter one if none are found too

**Comment by Grey-Lancaster** [comment]
-- host works
